
spring.application.name=auto-prime-api

# Banco de Dados - SQL Server
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=Loja_carros;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Porta
server.port=8080
